# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: IPv4
open_collective: # Replace with a single Open Collective username
ko_fi: MattIPv4
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://paypal.me/MattIPv4Cowley
