name = "dns-over-discord"
main = "dist/worker.js"
account_id = "fb1f542488f2441acf88ca15f3a8390d"
workers_dev = true
compatibility_date = "2021-10-17"
kv_namespaces = [
    { binding = "CACHE", id = "49442b14c2cb482ea086750526022d3e", preview_id = "49442b14c2cb482ea086750526022d3e" }
]

[build]
command = "npm run build"
watch_dir = "src"

[env.staging]
workers_dev = false
route = "dns-over-discord-staging.v4.wtf/*"
kv_namespaces = [
    { binding = "CACHE", id = "a4e14492f7624d39810022793969428b" }
]

[env.production]
workers_dev = false
route = "dns-over-discord.v4.wtf/*"
kv_namespaces = [
    { binding = "CACHE", id = "ac1c24f2c9594a97aeb7dd30377b45ef" }
]
