name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v1

      - name: Render .env
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_PUBLIC_KEY: ${{ secrets.CLIENT_PUBLIC_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: envsubst < production.env.sample > production.env

      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
